Installer custom actions
Particular/ServiceControl pull request #2350
Opened 2020-12-07 12:08 UTC by HEskandari

This contains the following:

- Install the PowerShell modules to a folder and adds to PSModulesPath environment variable
- Bump the PowerShell project target framework to net462
- Fix relative path to zip installer files when accessing from PowerShell
- Logging module/installer paths
- Logging errors when the installer fails

2020-12-08 08:01 UTC, ramonsmits requested changes

2020-12-08 08:01 UTC, ramonsmits commented on src/ServiceControlInstaller.PowerShell/Cmdlets/ServiceControlInstances/NewServiceControlInstance.cs
> +            var zipfolder = Path.Combine(modulePath, "..");
Refactor shared zip location resolve logic.

2020-12-08 08:01 UTC, ramonsmits commented on src/ServiceControlInstaller.PowerShell/Cmdlets/ServiceControlInstances/InvokeServiceControlInstanceUpgrade.cs
> +            var zipFolder = Path.Combine(Path.GetDirectoryName(MyInvocation.MyCommand.Module.Path), "..");
Refactor shared zip location resolve logic.

2020-12-08 11:05 UTC, ramonsmits commented
@HEskandari applied the zip folder refactoring. Applied additional changes for zip folders in commit afd0001027955b57f9c1735d0bdf80119bd4d36e but not sure if needed.

2020-12-14 05:27 UTC, mauroservienti approved these changes

2020-12-14 08:36 UTC, ramonsmits approved these changes

2020-12-15 06:48 UTC, merged