Update framework version to 472
Particular/ServiceControl pull request #2390
Opened 2021-01-13 12:21 UTC by WilliamBZA

Fixes https://github.com/Particular/ServiceControl/issues/2389

2021-01-13 14:48 UTC, mauroservienti approved these changes

2021-01-13 14:53 UTC, dvdstelt requested changes
Did you test this? Because according [to this document](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-472) it doesn't work. And it was also what we tested.

2021-01-13 15:26 UTC, ramonsmits commented
Yeah, that didn't work. Its the same as https://github.com/Particular/ServiceControl/pull/2384 and tried modifying the base image in that PR too.

2021-01-13 15:31 UTC, ramonsmits commented
So we can merge this as this should be fixed anyway but it is not enough to restore docker support. I've removed the fixes thingy in the description as it doesn't fix this.

2021-01-13 15:31 UTC, ramonsmits submitted a review, later dismissed

2021-01-13 15:46 UTC, dvdstelt approved these changes

2021-01-14 07:00 UTC, WilliamBZA commented
I pushed changes to install net472 in the containers. Tested locally using rabbitconventional.

2021-01-14 08:54 UTC, danielmarbach commented
So out of curiousity why is it better to rely on a script we copy pasted from the image instead of directly updating the base image to the one that supports .NET 4.7.2 as outlined in https://github.com/Particular/ServiceControl/pull/2384 ?

2021-01-14 09:28 UTC, ramonsmits commented
> So out of curiousity why is it better to rely on a script we copy pasted from the image instead of directly updating the base image to the one that supports .NET 4.7.2 as outlined in #2384 ?

This isn't ready for merging unless multiple transports have been tested. Also, this would require us to keep updating this for every security update and it also considerably delays the build.

2021-01-14 09:31 UTC, WilliamBZA commented
Closing. More than 4 hours has been collectively spent on this so it is clearly not a small task.

2021-01-14 09:31 UTC, closed without merging

2021-01-14 09:34 UTC, ramonsmits commented
I just tested this with ASBS and I get the same errors as with #2384 

```
Attaching to particularplatform_audit_1, particularplatform_monitoring_1, particularplatform_error_1
monitoring_1  | 2021-01-14 10:30:50.3800|1|Info|LoggingConfiguration|Logging to C:\Data\Logs\logfile.2021-01-14.txt with LogLevel 'Warn'
audit_1       | 2021-01-14 10:30:50.3354|1|Info|ServiceControl.Audit.Infrastructure.Settings.Settings|No settings found for audit log queue to import, default name will be used
monitoring_1  | System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
monitoring_1  |    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
monitoring_1  |    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
monitoring_1  |    at ServiceControl.Monitoring.Bootstrapper.RegisterInternalWebApiControllers(ContainerBuilder containerBuilder) in /_/src/ServiceControl.Monitoring/Bootstrapper.cs:line 107
monitoring_1  |    at ServiceControl.Monitoring.Bootstrapper.Initialize(EndpointConfiguration config) in /_/src/ServiceControl.Monitoring/Bootstrapper.cs:line 94
monitoring_1  |    at ServiceControl.Monitoring.SetupCommand.Execute(Settings settings) in /_/src/ServiceControl.Monitoring/Hosting/Commands/SetupCommand.cs:line 17
monitoring_1  |    at ServiceControl.Monitoring.CommandRunner.<Run>d__1.MoveNext() in /_/src/ServiceControl.Monitoring/Hosting/Commands/CommandRunner.cs:line 16
monitoring_1  | --- End of stack trace from previous location where exception was thrown ---
monitoring_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
monitoring_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
monitoring_1  |    at ServiceControl.Monitoring.Program.Main(String[] args) in /_/src/ServiceControl.Monitoring/Program.cs:line 26
audit_1       |
audit_1       | Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
audit_1       |    at NServiceBus.Transport.AzureServiceBus.AzureServiceBusTransportInfrastructure..ctor(SettingsHolder settings, String connectionString)
audit_1       |    at NServiceBus.AzureServiceBusTransport.Initialize(SettingsHolder settings, String connectionString)
audit_1       |    at NServiceBus.Raw.InitializableRawEndpoint.<Initialize>d__1.MoveNext()
audit_1       | --- End of stack trace from previous location where exception was thrown ---
audit_1       |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
audit_1       |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
audit_1       |    at ServiceControl.Audit.Infrastructure.SetupBootstrapper.<Run>d__1.MoveNext() in /_/src/ServiceControl.Audit/Infrastructure/SetupBootstrapper.cs:line 61
audit_1       | --- End of stack trace from previous location where exception was thrown ---
audit_1       |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
audit_1       |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
audit_1       |    at ServiceControl.Audit.Infrastructure.Hosting.Commands.SetupCommand.<Execute>d__0.MoveNext() in /_/src/ServiceControl.Audit/Infrastructure/Hosting/Commands/SetupCommand.cs:line 10
audit_1       | --- End of stack trace from previous location where exception was thrown ---
audit_1       |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
audit_1       |    at ServiceControl.Audit.Infrastructure.Hosting.Commands.CommandRunner.<Execute>d__1.MoveNext() in /_/src/ServiceControl.Audit/Infrastructure/Hosting/Commands/CommandRunner.cs:line 19
audit_1       | --- End of stack trace from previous location where exception was thrown ---
audit_1       |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
audit_1       |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
audit_1       |    at ServiceControl.Audit.Program.<Main>d__0.MoveNext() in /_/src/ServiceControl.Audit/Program.cs:line 29
audit_1       | --- End of stack trace from previous location where exception was thrown ---
audit_1       |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
audit_1       |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
audit_1       |    at ServiceControl.Audit.Program.<Main>(String[] args)
error_1       | 2021-01-14 10:30:51.2421|1|Info|ServiceBus.Management.Infrastructure.Settings.Settings|No settings found for error log queue to import, default name will be used
error_1       |
error_1       | Unhandled Exception:
particularplatform_error_1 exited with code 255
particularplatform_monitoring_1 exited with code 4294967295
particularplatform_audit_1 exited with code 255
```