Updated the shell title to Service Control Management Fixes #2596
Particular/ServiceControl pull request #3193
Opened 2022-11-10 14:32 UTC by awright18

2022-11-10 17:02 UTC, WilliamBZA approved these changes

2022-11-10 22:02 UTC, bording requested changes

2022-11-10 22:02 UTC, bording commented on src/ServiceControl.Config/UI/Shell/ShellView.xaml
> +                      Title="Service Control Management"
```suggestion
                      Title="ServiceControl Management"
```

2022-11-11 21:27 UTC, bording approved these changes

2022-11-11 22:05 UTC, merged