Use chiseled base image
Particular/ServiceControl pull request #4354
Opened 2024-08-08 21:31 UTC by DavidBoike

2024-08-08 22:01 UTC, bording requested changes

2024-08-08 22:01 UTC, bording commented on src/ServiceControl.Monitoring/Dockerfile
> +COPY --from=build /deploy/healthcheck ./healthcheck
```suggestion
COPY --from=build /healthcheck /healthcheck
```

2024-08-08 22:01 UTC, bording commented on src/ServiceControl/Dockerfile
> +COPY --from=build /deploy/healthcheck ./healthcheck
```suggestion
COPY --from=build /healthcheck /healthcheck
```

2024-08-08 22:01 UTC, bording commented on src/HealthCheckApp/HealthCheckApp.csproj
> +    <Artifact Include="$(OutputPath)" FileExclude="ServiceControl.dll.config;nsb*.txt" DirExclude=".db;.logs" DestinationFolder="$(ArtifactsPath)healthcheck" />
We can remove this entirely if we decide to take my suggested changes to the Dockerfiles.

2024-08-08 22:01 UTC, bording commented on src/HealthCheckApp/HealthCheckApp.csproj
> +    <TargetFramework>net8.0</TargetFramework>
Nit: Let's move this up to the top, and move `AssemblyName` to the bottom.

2024-08-08 22:04 UTC, DavidBoike commented on src/HealthCheckApp/Program.cs
> +Console.WriteLine("OK");
You do get this:

```
"Log": [
{
	"Start": "2024-08-08T22:00:18.440376136Z",
	"End": "2024-08-08T22:00:18.61019214Z",
	"ExitCode": 0,
	"Output": "OK\n"
},
{
	"Start": "2024-08-08T22:00:48.612150175Z",
	"End": "2024-08-08T22:00:48.786716911Z",
	"ExitCode": 0,
	"Output": "OK\n"
},
{ …
```

You can't get away from having the Output property in there though, such as `"Output": ""` as we did previously when we were sending the wget output to /dev/null

2024-08-08 22:11 UTC, boblangley commented on src/HealthCheckApp/Program.cs
> +Console.WriteLine("OK");
> To help debug failing probes, any output text (UTF-8 encoded) that the command writes on stdout or stderr will be stored in the health status and can be queried with docker inspect. Such output should be kept short (only the first 4096 bytes are stored currently).

It doesn't look like this goes into the normal logs and should be OK.

2024-08-08 22:12 UTC, boblangley approved these changes

2024-08-09 16:09 UTC, bording approved these changes

2024-08-09 16:31 UTC, boblangley approved these changes

2024-08-09 16:43 UTC, merged